### ISSUE TITLE
TEMPO REAL

### ISSUE THREAD

**Issue by ghost** [viniciuscbb/bot-sinais-2.0#12]
O bot quase sempre para a contagem dos segundos antes do sinal, se for um sinal muito longe de se iniciar, ele trava e necessita de um Ctrl + C para destravar, algumas vezes ele até encerra.

E se estiver travado, quando der o horário do sinal, ele não reconhece e não entra.

**Comment by jeffex** [comment]
> O bot quase sempre para a contagem dos segundos antes do sinal, se for um sinal muito longe de se iniciar, ele trava e necessita de um Ctrl + C para destravar, algumas vezes ele até encerra.
> 
> E se estiver travado, quando der o horário do sinal, ele não reconhece e não entra.

Há algumas breves paradas antes do sinal para pegar algumas informações, como por exemplo o payout e verificar se a paridade esta aberta. Nesse momento, o contador para mas assim que as informações são obtidas ele volta a contagem. O contador para pela primeira vez faltando 52 segundos para a hora da entrada, e leva em média uns 15 segundos pra retornar a contagem. Depois para novamente faltando 32 segundos para a entrada, e leva menos de 5 segundos pra retornar a contagem.
