### ISSUE TITLE
Não mostra o próximo sinal

### ISSUE THREAD

**Issue by ghost** [viniciuscbb/bot-sinais-2.0#16]
Se o sinal for cancelado por alguns dos filtros: hit de vela, notícias, tendência e etc...
Ele não mostra o próximo sinal, ele repete o mesmo sinal.

SINAIS PENDENTES: 3
PRÓXIMO SINAL: EURUSD | M1 | 17:30 | PUT
PARIDADE EURUSD COM PAYOUT ABAIXO DO MÍNIMO ESTABELECIDO!

SINAIS PENDENTES: 3
PRÓXIMO SINAL: EURUSD | M1 | 17:30 | PUT

**Comment by williamfc05** [comment]
Esse problema eu consegui resolver chamando a função buscarMenor() antes da função de ir pro próximo sinal, após o tratamento de cada erro de entrada, exemplo na imagem:

**Comment by williamfc05** [comment]
Esse problema eu consegui resolver chamando a função buscarMenor() antes da função de ir pro próximo sinal, após o tratamento de cada erro de entrada, exemplo na imagem: ![image](https://user-images.githubusercontent.com/52292968/116587482-e145d680-a8f0-11eb-80d4-4e38cc887e2a.png)

**Comment by ghost** [comment]
> 
> 
> Esse problema eu consegui resolver chamando a função buscarMenor() antes da função de ir pro próximo sinal, após o tratamento de cada erro de entrada, exemplo na imagem: ![image](https://user-images.githubusercontent.com/52292968/116587482-e145d680-a8f0-11eb-80d4-4e38cc887e2a.png)

Obrigado! Estarei aplicando a correção.
