### ISSUE TITLE
Martingale dont work

### ISSUE THREAD

**Issue by dremiski** [viniciuscbb/bot-sinais-2.0#3]
Hello guys, 

I'm testing the bot, it's getting excellent,
but i see that the martingale and nextsignal is not working properly.

**Comment by viniciuscbb** [comment]
> Hello guys,
> 
> I'm testing the bot, it's getting excellent,
> but i see that the martingale and nextsignal is not working properly.

To use the MartinGale next signal you must disable the first MartinGale.

Example:
martingale = N
mgProxSinal = S

**Comment by dremiski** [comment]
![image](https://user-images.githubusercontent.com/64877442/106298337-88539d00-6232-11eb-9198-89f6c4592a49.png)

Here doesnt work, with your config

Aqui não funcionou, com o seu exemplo

**Comment by jeffex** [comment]
> ![image](https://user-images.githubusercontent.com/64877442/106298337-88539d00-6232-11eb-9198-89f6c4592a49.png)
> 
> Here doesnt work, with your config
> 
> Aqui não funcionou, com o seu exemplo

could you show me your configuration file (config.txt). Both martingale are working perfectly here.
PS: don't forget to hide your personal information
