### ISSUE TITLE
Bot saying that Pairs are close, but are open

### ISSUE THREAD

**Issue by oppalla** [viniciuscbb/bot-sinais-2.0#6]
Today I've left the bot to run the first tests with real signals.
Except today, it was running fine with signals I've made for testing, like 30 signals per hour from two to two minutes.
But today, for M5 and M15 signals, the bot says that most of the pairs are closed. But they're just closed on digital options.
It says like:

> SINAIS PENDENTES: 7
> PROXIMO: CADCHF | TEMPO: M15 | HORA: 13:45 | DIREÇÃO: CALL
>  PARIDADE CADCHF FECHADA!!
> 
> ERRO AO REALIZAR ENTRADA!!
> SINAIS PENDENTES: 6
> PROXIMO: GBPUSD | TEMPO: M15 | HORA: 14:00 | DIREÇÃO: PUT
> 01/02/2021 13:48:50

and it just doesn't does the entry.
am I missing something?

my settings now are like:

> [GERAL]
> entrada = 212
> conta = PRACTICE
> # PRACTICE / REAL
> 
> stop_win = 1505
> stop_loss = 635
> trailing_stop = N
> trailing_stop_valor = 1000000000
> 
> martingale = S
> mgProxSinal = N
> valorGale = 2
> niveis = 1
> 
> analisarTendencia = N
> noticias = N
> hitVela = N
> 
> [telegram]
> telegram_token = XXXXXXX:XXXXXXX
> telegram_id = XXXXXXX
> usar_bot = S
> 
> [CONTA]
> email = XXXXXXXXXXX
> senha = XXXXXXXXXX

thank you guys. @jeffex @viniciuscbb

**Comment by oppalla** [comment]
Traceback (most recent call last):
  File "/Users/User/Desktop/botsinais/main.py", line 530, in <module>
    operar(valor_entrada, par, direcao, timeframe, horario, opcao)
NameError: name 'opcao' is not defined

**Comment by jeffex** [comment]
I made some changes to the function of checking the payout. I haven't tested this question of parity closed in digital and open in binary. I will run tests on this, but maybe with the changes I made it I have already solved it. Use the latest bot update and check if the problem persists. I made a pull request so you will have to wait for Vinicius to merge with the latest changes

**Comment by oppalla** [comment]
thank you @jeffex . I'll wait so, for @viniciuscbb to release your pull request with the new changes.
hope we can make this work smoothly
I'll put my efforts as long as I can on it

**Comment by jeffex** [comment]
@oppalla I took a test now and found that the problem still persists. As soon as possible I will make the correction.

**Comment by oppalla** [comment]
@jeffex I've downloaded from your fork, and attested the problem still persists :(
I've found another .py bot on MercadoLivre that works, maybe you will like to take a look at the code. is there any way to contact you via telegram or whatsapp?

**Comment by jeffex** [comment]
> @jeffex I've downloaded from your fork, and attested the problem still persists :(
> I've found another .py bot on MercadoLivre that works, maybe you will like to take a look at the code. is there any way to contact you via telegram or whatsapp?

I believe I know what's going on and how to fix it, but at the moment I'm out of time. I will try to perform the correction this week

**Comment by trombini77** [comment]
Hi, I saw all messages and I have some doubts at this moment:
- does exist a feature in the bot that check if a pair is available in digital or binary following a preference?
- if not today it always looking for digital, at least in my test is what it showed to me right?
- the issue opened is requesting something like this to check in both (digital and binary) right?
- one suggestion to implement also would be select the pair based in the who has more payout also using the minimal payout parameter (config.txt payout parameter)
I would like to help in the development of this code do you see any problem?
Thanks.

**Comment by jeffex** [comment]
> Hi, I saw all messages and I have some doubts at this moment:
> 
> * does exist a feature in the bot that check if a pair is available in digital or binary following a preference?
> * if not today it always looking for digital, at least in my test is what it showed to me right?
> * the issue opened is requesting something like this to check in both (digital and binary) right?
> * one suggestion to implement also would be select the pair based in the who has more payout also using the minimal payout parameter (config.txt payout parameter)
>   I would like to help in the development of this code do you see any problem?
>   Thanks.

Hi.
Yes, the bot checks whether the parity is open in digital or binary and checks your payouts and selects the type with the best payout. However there is a problem when the parity is open in binary but closed in digital, the bot returns as the parity is closed. By default, if the payouts are the same, the entry goes without binary type.
Feel free to collaborate with the project.

**Comment by trombini77** [comment]
> > Hi, I saw all messages and I have some doubts at this moment:
> > 
> > * does exist a feature in the bot that check if a pair is available in digital or binary following a preference?
> > * if not today it always looking for digital, at least in my test is what it showed to me right?
> > * the issue opened is requesting something like this to check in both (digital and binary) right?
> > * one suggestion to implement also would be select the pair based in the who has more payout also using the minimal payout parameter (config.txt payout parameter)
> >   I would like to help in the development of this code do you see any problem?
> >   Thanks.
> 
> Hi.
> Yes, the bot checks whether the parity is open in digital or binary and checks your payouts and selects the type with the best payout. However there is a problem when the parity is open in binary but closed in digital, the bot returns as the parity is closed. By default, if the payouts are the same, the entry goes without binary type.
> Feel free to collaborate with the project.

I did yesterday some changes that is not only this issue opened and I fix the check_profile. I added also support to send all menssages to Telegram bot.
Anyway I found other issue but is with the API library that is refusing any API.buy when is possible to do it.
I opened a issue in API library repository asking about it with logging data of data sent.
I hope send my suggestions soon here in a PR ;)

**Comment by jeffex** [comment]
@oppalla I believe I have solved this problem. At least in my tests here I have not seen more. Could you test my fork? If you confirm the resolution of the problem I will make the pull request.
