### ISSUE TITLE
Payout Problem

### ISSUE THREAD

**Issue by ghost** [viniciuscbb/bot-sinais-2.0#8]
Traceback (most recent call last):
  File "main.py", line 612, in <module>
    elif par not in paridades_fechadas and payout >= payout_minimo:
NameError: name 'payout' is not defined

**Comment by weldevan** [comment]
Boa noite! que tipo de erro e esse
AppData\Local\Temp_MEI84402\dateutil\zoneinfo_init_.py:26: UserWarning: I/O error(2): No such file or directory,
https://prnt.sc/yw246z
quando eu transformo ele em executável

**Comment by ghost** [comment]
> 
> 
> Boa noite! que tipo de erro e esse
> AppData\Local\Temp_MEI84402\dateutil\zoneinfo_init_.py:26: UserWarning: I/O error(2): No such file or directory,
> https://prnt.sc/yw246z
> quando eu transformo ele em executável

Utilize o "auto-py-to-exe", e transforme em um "one file" executável. Se não resolver, apenas reinstale o deteutil no seu computador.

**Comment by weldevan** [comment]
a versão do python-dateutil 2.8.1 e eu ja tentei  transforme em executável pelo auto-py-to-exe o erro esta o mesmo :/
AppData\Local\Temp_MEI84402\dateutil\zoneinfo_init_.py:26: UserWarning: I/O error(2): No such file or directory,
https://prnt.sc/yw246z

**Comment by weldevan** [comment]
consegui vlwww

**Comment by jeffex** [comment]
> Traceback (most recent call last):
> File "main.py", line 612, in
> elif par not in paridades_fechadas and payout >= payout_minimo:
> NameError: name 'payout' is not defined

@misterfacal o problema ainda persiste? Qual API voce esta usando?

**Comment by ghost** [comment]
> 
> 
> > Traceback (most recent call last):
> > File "main.py", line 612, in
> > elif par not in paridades_fechadas and payout >= payout_minimo:
> > NameError: name 'payout' is not defined
> 
> @misterfacal o problema ainda persiste? Qual API voce esta usando?

Tudo bem?
Até então só aconteceu 3 vezes, mas aparentemente está estável. Utilizo a API do Faria.
