### ISSUE TITLE
Tempo de entrada dos Martingale

### ISSUE THREAD

**Issue by trombini77** [viniciuscbb/bot-sinais-2.0#9]
Olá a todos.
Primeiramente parabéns pelo trabalho.
Fiz um fork do projeto espero contribuir em breve com ele.
Fiz meu primeiro teste com uma lista desde as 00:00 de hoje 8/2/2021.
Uma coisa que notei por exemplo com os Martingale é que eles entraram de 4 a 5 segundos após o tempo que deveria ser.

Exemplo:
no lista.csv tem a seguinte linha:
M15;EURUSD;00:30;PUT

e no config.txt tem o seguitne setup:
martingale = S
mgProxSinal = N
valorGale = 2.3
niveis = 2

![image](https://user-images.githubusercontent.com/13336060/107213365-09efbb80-69e7-11eb-8c29-1fcf968f2afd.png)
![image](https://user-images.githubusercontent.com/13336060/107213397-1a079b00-69e7-11eb-918c-f96cc0213dc6.png)
![image](https://user-images.githubusercontent.com/13336060/107213436-2b50a780-69e7-11eb-90c4-beee29639b6c.png)

É algum setup errado ou é necessário um ajujste?
Se é necessário um ajuste para isso posso ajudar?
Abraços

**Comment by viniciuscbb** [comment]
Olá, como não existe uma API oficial pela IQ Option, é utilizado uma não oficial que funciona por meio de web request, com isso ela gera delay em realizar uma operação. Tentei resolver o delay realizando a entrada 2 segundos antes do início da vela que por fim funcionar certamente, porém na função de Martingale ele precisa esperar o resultado da operação e logo realizar o gale e acaba gerando delay.

Uma solução que eu desenvolvi e que uso em meu bot pago é verificar a cor da vela 3 segundos antes dela fechar e realizar o Martingale em cima desse resultado, porém pode realizar o gale errôneo caso a vela vire nos últimos 3 segundos. Essa função não consta nessa versão do bot-sinais-2.0 .
